import type {User, Project, Team, Sprint, Issue, ProjectStatus, IssueTemplate} from "@/types"

// Centralized demo data for initial hydration

export const demoUsers: User[] = [
  {
    id: "user-1",
    name: "Alice Johnson",
    email: "alice@example.com",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: "user-2",
    name: "Bob Smith",
    email: "bob@example.com",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: "user-3",
    name: "Carol Williams",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: "user-4",
    name: "Charlie Brown",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: "user-5",
    name: "Diana Prince",
    email: "diana@example.com",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
]

// Users referenced by demo issues
const referencedUserIds = ["user-1", "user-2", "user-4", "user-5"]

export const demoProjects: Project[] = [
  {
    id: "proj-1",
    name: "Main Project",
    status: "Active" as ProjectStatus,
    startDate: "2025-01-01",
    members: referencedUserIds.slice(),
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
]

export const demoTeams: Team[] = [
  {
    id: "team-1",
    name: "Main Team",
    members: referencedUserIds.slice(),
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
]

export const demoSprints: Sprint[] = [
  {
    id: "sprint-1",
    name: "Sprint 1 - Foundation",
    status: "Completed",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-14"),
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-01-14"),
  },
  {
    id: "sprint-2",
    name: "Sprint 2 - Core Features",
    status: "Active",
    startDate: new Date("2024-01-15"),
    endDate: new Date("2024-01-28"),
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "sprint-3",
    name: "Sprint 3 - Polish & Testing",
    status: "Planned",
    startDate: new Date("2024-01-29"),
    endDate: new Date("2024-02-11"),
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
]

export const demoIssues: Issue[] = [
  // Completed sprint issues
  {
    id: "TSK-001",
    title: "Setup project structure",
    description: "Initialize the project with proper folder structure and dependencies",
    priority: "P1",
    status: "Done",
    assigneeUserId: "user-1",
    sprintId: "sprint-1",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "TSK-002",
    title: "Design system components",
    description: "Create reusable UI components following design system",
    priority: "P2",
    status: "Done",
    assigneeUserId: "user-2",
    sprintId: "sprint-1",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2023-12-29"),
    updatedAt: new Date("2024-01-08"),
  },
  {
    id: "TSK-003",
    title: "Database schema design",
    description: "Design and implement the database schema for the application",
    priority: "P1",
    status: "Done",
    assigneeUserId: "user-4",
    sprintId: "sprint-1",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2023-12-30"),
    updatedAt: new Date("2024-01-10"),
  },

  // Active sprint issues
  {
    id: "TSK-004",
    title: "User authentication system",
    description: "Implement login, registration, and session management",
    priority: "P0",
    status: "In Progress",
    assigneeUserId: "user-1",
    sprintId: "sprint-2",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "TSK-005",
    title: "Dashboard layout",
    description: "Create the main dashboard with navigation and layout components",
    priority: "P1",
    status: "In Review",
    assigneeUserId: "user-2",
    sprintId: "sprint-2",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-11"),
    updatedAt: new Date("2024-01-19"),
  },
  {
    id: "TSK-006",
    title: "API endpoints for tasks",
    description: "Develop REST API endpoints for CRUD operations on tasks",
    priority: "P1",
    status: "Todo",
    assigneeUserId: "user-4",
    sprintId: "sprint-2",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "TSK-007",
    title: "Real-time notifications",
    description: "Implement WebSocket-based real-time notifications",
    priority: "P2",
    status: "Todo",
    assigneeUserId: "user-5",
    sprintId: "sprint-2",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-13"),
    updatedAt: new Date("2024-01-13"),
  },

  // Planned sprint issues
  {
    id: "TSK-008",
    title: "Performance optimization",
    description: "Optimize application performance and loading times",
    priority: "P2",
    status: "Todo",
    assigneeUserId: "user-1",
    sprintId: "sprint-3",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "TSK-009",
    title: "Unit test coverage",
    description: "Write comprehensive unit tests for all components",
    priority: "P3",
    status: "Todo",
    assigneeUserId: "user-2",
    sprintId: "sprint-3",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-21"),
    updatedAt: new Date("2024-01-21"),
  },

  // Backlog issues (no sprint)
  {
    id: "TSK-010",
    title: "Mobile responsive design",
    description: "Ensure the application works well on mobile devices",
    priority: "P2",
    status: "Todo",
    assigneeUserId: "user-4",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "TSK-011",
    title: "Dark mode support",
    description: "Add dark mode theme support throughout the application",
    priority: "P3",
    status: "Todo",
    assigneeUserId: "user-5",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
  },
  {
    id: "TSK-012",
    title: "Export functionality",
    description: "Allow users to export their data in various formats",
    priority: "P4",
    status: "Todo",
    assigneeUserId: "user-1",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17"),
  },
  {
    id: "TSK-013",
    title: "Advanced search filters",
    description: "Implement advanced filtering and search capabilities",
    priority: "P3",
    status: "Todo",
    assigneeUserId: "user-2",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "TSK-014",
    title: "Integration with external tools",
    description: "Add integrations with popular project management tools",
    priority: "P4",
    status: "Todo",
    assigneeUserId: "user-4",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19"),
  },
  {
    id: "TSK-015",
    title: "User onboarding flow",
    description: "Create guided onboarding experience for new users",
    priority: "P2",
    status: "Todo",
    assigneeUserId: "user-5",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "TSK-016",
    title: "Analytics dashboard",
    description: "Build analytics dashboard with project insights and metrics",
    priority: "P5",
    status: "Todo",
    assigneeUserId: "user-1",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-21"),
    updatedAt: new Date("2024-01-21"),
  },
]


export const demoIssueTemplates: IssueTemplate[] = [
  {
    id: "bug",
    name: "Bug",
    prefix: "[Bug] ",
    isDefault: false,
    defaults: {
      priority: "P1",
      status: "Todo",
      defaultAssigneeUserId: "user-1", // Alice Johnson
    },
    acceptanceCriteria: [
      "Steps to reproduce defined",
      "Expected vs actual behavior described",
      "Reproduction confirmed",
    ],
  },
  {
    id: "feature",
    name: "Feature",
    prefix: "[Feature] ",
    isDefault: true,
    defaults: {
      priority: "P3",
      status: "Todo",
      defaultAssigneeUserId: "user-2", // Bob Smith
    },
    acceptanceCriteria: [
      "Acceptance scenarios listed",
      "Non-functional constraints noted",
      "UX mock agreed",
    ],
  },
  {
    id: "request",
    name: "Request",
    prefix: "[Request] ",
    isDefault: false,
    defaults: {
      priority: "P2",
      status: "Todo",
      defaultAssigneeUserId: "user-4", // Charlie Brown
    },
    acceptanceCriteria: [
      "User impact clarified",
      "Success criteria measurable",
      "Approver identified",
    ],
  },
]
