import type { User, Project, Team, Sprint, Issue, ProjectStatus } from "@/types"

// Helper functions for dynamic date generation
const today = new Date()
const daysAgo = (n: number) => {
  const d = new Date(today)
  d.setDate(d.getDate() - n)
  return d
}
const isoDaysAgo = (n: number) => daysAgo(n).toISOString()

// Centralized demo data for initial hydration

export const demoUsers: User[] = [
  {
    id: "user-1",
    name: "Alice Johnson",
    email: "alice@example.com",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "user-2",
    name: "Bob Smith",
    email: "bob@example.com",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "user-3",
    name: "Carol Williams",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "user-4",
    name: "Charlie Brown",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "user-5",
    name: "Diana Prince",
    email: "diana@example.com",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
]

// Users referenced by demo issues
const referencedUserIds = ["user-1", "user-2", "user-4", "user-5"]

export const demoProjects: Project[] = [
  {
    id: "proj-1",
    name: "Main Project",
    status: "Active" as ProjectStatus,
    startDate: "2025-01-01",
    members: referencedUserIds.slice(),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
]

export const demoTeams: Team[] = [
  {
    id: "team-1",
    name: "Main Team",
    members: referencedUserIds.slice(),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
]

export const demoSprints: Sprint[] = [
  {
    id: "sprint-1",
    name: "Sprint 1 - Foundation",
    status: "Completed",
    startDate: daysAgo(28),
    endDate: daysAgo(21),
    createdAt: daysAgo(29),
    updatedAt: daysAgo(21),
  },
  {
    id: "sprint-2",
    name: "Sprint 2 - Core Features",
    status: "Active",
    startDate: daysAgo(20),
    endDate: daysAgo(7),
    createdAt: daysAgo(22),
    updatedAt: daysAgo(20),
  },
  {
    id: "sprint-3",
    name: "Sprint 3 - Polish & Testing",
    status: "Planned",
    startDate: daysAgo(6),
    endDate: daysAgo(0),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
]

export const demoIssues: Issue[] = [
  // Completed sprint issues
  {
    id: "TSK-001",
    title: "Setup project structure",
    description: "Initialize the project with proper folder structure and dependencies",
    priority: "P1",
    status: "Done",
    assigneeUserId: "user-1",
    sprintId: "sprint-1",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(29),
    updatedAt: daysAgo(25),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(29) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(28) },
      { from: "In Progress", to: "In Review", atISO: isoDaysAgo(27) },
      { from: "In Review", to: "Done", atISO: isoDaysAgo(25) },
    ],
  },
  {
    id: "TSK-002",
    title: "Design system components",
    description: "Create reusable UI components following design system",
    priority: "P2",
    status: "Done",
    assigneeUserId: "user-2",
    sprintId: "sprint-1",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(28),
    updatedAt: daysAgo(22),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(28) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(27) },
      { from: "In Progress", to: "In Review", atISO: isoDaysAgo(25) },
      { from: "In Review", to: "Done", atISO: isoDaysAgo(22) },
    ],
  },
  {
    id: "TSK-003",
    title: "Database schema design",
    description: "Design and implement the database schema for the application",
    priority: "P1",
    status: "Done",
    assigneeUserId: "user-4",
    sprintId: "sprint-1",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(27),
    updatedAt: daysAgo(20),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(27) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(26) },
      { from: "In Progress", to: "In Review", atISO: isoDaysAgo(23) },
      { from: "In Review", to: "Done", atISO: isoDaysAgo(20) },
    ],
  },

  // Active sprint issues
  {
    id: "TSK-004",
    title: "User authentication system",
    description: "Implement login, registration, and session management",
    priority: "P0",
    status: "In Progress",
    assigneeUserId: "user-1",
    sprintId: "sprint-2",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(19),
    updatedAt: daysAgo(15),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(19) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(15) },
    ],
  },
  {
    id: "TSK-005",
    title: "Dashboard layout",
    description: "Create the main dashboard with navigation and layout components",
    priority: "P1",
    status: "In Review",
    assigneeUserId: "user-2",
    sprintId: "sprint-2",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(14),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(18) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(16) },
      { from: "In Progress", to: "In Review", atISO: isoDaysAgo(14) },
    ],
  },
  {
    id: "TSK-006",
    title: "API endpoints for tasks",
    description: "Develop REST API endpoints for CRUD operations on tasks",
    priority: "P1",
    status: "Todo",
    assigneeUserId: "user-4",
    sprintId: "sprint-2",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(17),
    updatedAt: daysAgo(17),
  },
  {
    id: "TSK-007",
    title: "Real-time notifications",
    description: "Implement WebSocket-based real-time notifications",
    priority: "P2",
    status: "Todo",
    assigneeUserId: "user-5",
    sprintId: "sprint-2",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(16),
    updatedAt: daysAgo(16),
  },

  // Planned sprint issues
  {
    id: "TSK-008",
    title: "Performance optimization",
    description: "Optimize application performance and loading times",
    priority: "P2",
    status: "Todo",
    assigneeUserId: "user-1",
    sprintId: "sprint-3",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "TSK-009",
    title: "Unit test coverage",
    description: "Write comprehensive unit tests for all components",
    priority: "P3",
    status: "Todo",
    assigneeUserId: "user-2",
    sprintId: "sprint-3",
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: new Date("2024-01-21"),
    updatedAt: new Date("2024-01-21"),
  },

  // Backlog issues (no sprint)
  {
    id: "TSK-010",
    title: "Mobile responsive design",
    description: "Ensure the application works well on mobile devices",
    priority: "P2",
    status: "Todo",
    assigneeUserId: "user-4",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },
  {
    id: "TSK-011",
    title: "Dark mode support",
    description: "Add dark mode theme support throughout the application",
    priority: "P3",
    status: "Todo",
    assigneeUserId: "user-5",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(13),
    updatedAt: daysAgo(13),
  },
  {
    id: "TSK-012",
    title: "Export functionality",
    description: "Allow users to export their data in various formats",
    priority: "P4",
    status: "Todo",
    assigneeUserId: "user-1",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
  {
    id: "TSK-013",
    title: "Advanced search filters",
    description: "Implement advanced filtering and search capabilities",
    priority: "P3",
    status: "Todo",
    assigneeUserId: "user-2",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(11),
    updatedAt: daysAgo(11),
  },
  {
    id: "TSK-014",
    title: "Integration with external tools",
    description: "Add integrations with popular project management tools",
    priority: "P4",
    status: "Todo",
    assigneeUserId: "user-4",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: "TSK-015",
    title: "User onboarding flow",
    description: "Create guided onboarding experience for new users",
    priority: "P2",
    status: "Todo",
    assigneeUserId: "user-5",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
  },
  {
    id: "TSK-016",
    title: "Analytics dashboard",
    description: "Build analytics dashboard with project insights and metrics",
    priority: "P5",
    status: "Todo",
    assigneeUserId: "user-1",
    sprintId: undefined,
    projectId: "proj-1",
    teamId: "team-1",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },
]
