import type {User, Project, Team, Sprint, Issue, ProjectStatus, IssueTemplate} from "@/types"

// Helper functions for dynamic date generation
const today = new Date()
const daysAgo = (n: number) => {
  const d = new Date(today)
  d.setDate(d.getDate() - n)
  return d
}
const isoDaysAgo = (n: number) => daysAgo(n).toISOString()

// Centralized demo data for initial hydration

export const demoUsers: User[] = [
  {
    id: "user-1",
    name: "Alice Johnson",
    email: "alice@example.com",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "user-2",
    name: "Bob Smith",
    email: "bob@example.com",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "user-3",
    name: "Carol Williams",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "user-4",
    name: "Charlie Brown",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "user-5",
    name: "Diana Prince",
    email: "diana@example.com",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
]

// Users referenced by demo issues
const referencedUserIds = ["user-1", "user-2", "user-3", "user-4", "user-5"]

export const demoProjects: Project[] = [
  {
    id: "proj-1",
    name: "FlowCraft V0",
    status: "Active" as ProjectStatus,
    startDate: "2025-01-01",
    members: referencedUserIds.slice(),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
]

export const demoTeams: Team[] = [
  {
    id: "team-prod",
    name: "Product Team",
    members: ["user-1", "user-5"], // Alice (PM), Diana (UX)
    createdAt: daysAgo(29),
    updatedAt: daysAgo(29),
  },
  {
    id: "team-dev",
    name: "Delivery Team",
    members: ["user-2", "user-3", "user-4"], // Bob (FE), Carol (QA), Charlie (FE/BE)
    createdAt: daysAgo(29),
    updatedAt: daysAgo(29),
  },
  {
    id: "team-1",
    name: "Main Team",
    members: referencedUserIds.slice(),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
]

export const demoSprints: Sprint[] = [
  {
    id: "sprint-0",
    name: "Sprint 0 — Discovery",
    status: "Completed",
    startDate: daysAgo(24),
    endDate: daysAgo(17),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(17),
  },
  {
    id: "sprint-1",
    name: "Sprint 1 — Experiments V0",
    status: "Active",
    startDate: daysAgo(10),
    endDate: daysAgo(-4), // ends in 4 days
    createdAt: daysAgo(11),
    updatedAt: daysAgo(1),
  },
  {
    id: "sprint-2",
    name: "Sprint 2 — Scaling Foundations",
    status: "Planned",
    startDate: daysAgo(-5), // starts in 5 days
    endDate: daysAgo(-12), // ends in 12 days
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
]

export const demoIssues: Issue[] = [
  // Sprint 0 — Product Team discovery (all done)
  {
    id: "TSK-101",
    title: "User interviews about FlowCraft value & churn drivers",
    description:
      "Summary: Conduct 6–8 stakeholder interviews; synthesize top churn drivers and desired outcomes. Ref: Discovery",
    priority: "P2",
    status: "Done",
    assigneeUserId: "user-1",
    sprintId: "sprint-0",
    projectId: "proj-1",
    teamId: "team-prod",
    createdAt: daysAgo(24),
    updatedAt: daysAgo(18),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(24) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(22) },
      { from: "In Progress", to: "In Review", atISO: isoDaysAgo(19) },
      { from: "In Review", to: "Done", atISO: isoDaysAgo(18) },
    ],
  },
  {
    id: "TSK-102",
    title: "Reddit posts analysis and problem collection",
    description:
      "Summary: Review competitor subreddits; collect and cluster pain points into themes. Ref: Discovery",
    priority: "P2",
    status: "Done",
    assigneeUserId: "user-5",
    sprintId: "sprint-0",
    projectId: "proj-1",
    teamId: "team-prod",
    createdAt: daysAgo(23),
    updatedAt: daysAgo(18),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(23) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(21) },
      { from: "In Progress", to: "In Review", atISO: isoDaysAgo(19) },
      { from: "In Review", to: "Done", atISO: isoDaysAgo(18) },
    ],
  },
  {
    id: "TSK-103",
    title: "Synthesize pain points and build Opportunity Solution Tree (OST)",
    description:
      "Summary: Produce OST linking opportunities to solutions (S1.x–S5.x). Deliver visual diagram + write‑up. Ref: OST",
    priority: "P1",
    status: "Done",
    assigneeUserId: "user-1",
    sprintId: "sprint-0",
    projectId: "proj-1",
    teamId: "team-prod",
    createdAt: daysAgo(22),
    updatedAt: daysAgo(17),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(22) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(20) },
      { from: "In Progress", to: "In Review", atISO: isoDaysAgo(18) },
      { from: "In Review", to: "Done", atISO: isoDaysAgo(17) },
    ],
  },
  {
    id: "TSK-104",
    title: "Design experiments for V0 prototype (S3.4+S4.3, S1.2, S2.1)",
    description:
      "Summary: Define 3 priority experiments: Quick Capture + Templates (S3.4+S4.3), Full Export (S1.2), Roll‑up Dashboard Lite (S2.1). Ref: product-experiments.md",
    priority: "P1",
    status: "Done",
    assigneeUserId: "user-5",
    sprintId: "sprint-0",
    projectId: "proj-1",
    teamId: "team-prod",
    createdAt: daysAgo(21),
    updatedAt: daysAgo(17),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(21) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(19) },
      { from: "In Progress", to: "In Review", atISO: isoDaysAgo(18) },
      { from: "In Review", to: "Done", atISO: isoDaysAgo(17) },
    ],
  },

  // Sprint 1 — Delivery team implementing Experiments (current)
  {
    id: "TSK-201",
    title: "Experiment: Quick Capture + Templates (S3.4 + S4.3)",
    description:
      "Summary: Implement Quick Add modal with templates and AC badges on cards. Ref: S3.4, S4.3. Delivered in 0.2.0",
    priority: "P1",
    status: "Done",
    assigneeUserId: "user-2",
    sprintId: "sprint-1",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(7),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(10) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(9) },
      { from: "In Progress", to: "In Review", atISO: isoDaysAgo(8) },
      { from: "In Review", to: "Done", atISO: isoDaysAgo(7) },
    ],
  },
  {
    id: "TSK-202",
    title: "Experiment: Roll‑up Dashboard (Lite) (S2.1)",
    description:
      "Summary: Add Dashboard view with status breakdown, sprint progress, throughput, and workload. Ref: S2.1. Delivered in 0.3.0",
    priority: "P1",
    status: "Done",
    assigneeUserId: "user-4",
    sprintId: "sprint-1",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(3),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(10) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(9) },
      { from: "In Progress", to: "In Review", atISO: isoDaysAgo(5) },
      { from: "In Review", to: "Done", atISO: isoDaysAgo(3) },
    ],
  },
  {
    id: "TSK-203",
    title: "Experiment: Full Export — JSON for Issues & Sprints (S1.2)",
    description:
      "Summary: Implement JSON export for Issues and Sprints; downloadable files. Ref: S1.2",
    priority: "P0",
    status: "In Progress",
    assigneeUserId: "user-4",
    sprintId: "sprint-1",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(1),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(6) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(2) },
    ],
  },
  {
    id: "TSK-204",
    title: "Experiment: Full Export — CSV for Issues & Sprints (S1.2)",
    description:
      "Summary: Implement CSV export for Issues and Sprints; ensure proper headers. Ref: S1.2",
    priority: "P1",
    status: "Todo",
    assigneeUserId: "user-2",
    sprintId: "sprint-1",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    id: "TSK-205",
    title: "Experiment: Export UI dropdown & download flow (S1.2)",
    description:
      "Summary: Add Export dropdown to toolbar; wire JSON/CSV downloads. Ref: S1.2",
    priority: "P1",
    status: "Todo",
    assigneeUserId: "user-2",
    sprintId: "sprint-1",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  // Recent fixes (0.4.1) to reflect current state
  {
    id: "TSK-206",
    title: "Fix: Issue search matches assignee names",
    description:
      "Summary: Include assignee names in search index and avoid duplicate mapping. Ref: 0.4.1",
    priority: "P2",
    status: "Done",
    assigneeUserId: "user-3",
    sprintId: "sprint-1",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(4) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(3) },
      { from: "In Progress", to: "In Review", atISO: isoDaysAgo(2) },
      { from: "In Review", to: "Done", atISO: isoDaysAgo(1) },
    ],
  },
  {
    id: "TSK-207",
    title: "Fix: Project/Team selectors and badges show names",
    description:
      "Summary: Ensure selectors always load and cards display correct names. Ref: 0.4.1",
    priority: "P2",
    status: "Done",
    assigneeUserId: "user-2",
    sprintId: "sprint-1",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
    statusChangeHistory: [
      { from: "Created", to: "Todo", atISO: isoDaysAgo(4) },
      { from: "Todo", to: "In Progress", atISO: isoDaysAgo(3) },
      { from: "In Progress", to: "In Review", atISO: isoDaysAgo(2) },
      { from: "In Review", to: "Done", atISO: isoDaysAgo(1) },
    ],
  },

  // Backlog (roadmap-derived, unscheduled)
  {
    id: "TSK-301",
    title: "UI/UX cleanup and progressive disclosure (S5.3)",
    description: "Summary: Improve clarity, reduce cognitive load, consistent patterns. Ref: S5.3",
    priority: "P1",
    status: "Todo",
    assigneeUserId: "user-5",
    projectId: "proj-1",
    teamId: "team-prod",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "TSK-302",
    title: "Visual indicators and badges for quick status read (S5.5)",
    description: "Summary: Add light charts/colors for status and progress. Ref: S5.5",
    priority: "P2",
    status: "Todo",
    assigneeUserId: "user-2",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "TSK-303",
    title: "Unified Inbox: aggregate mentions/notifications (S3.2)",
    description: "Summary: UI for central inbox and filters; no external APIs yet. Ref: S3.2",
    priority: "P2",
    status: "Todo",
    assigneeUserId: "user-2",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "TSK-304",
    title: "Task hierarchy: epics and subtasks (S4.2)",
    description: "Summary: Add parent-child relations and roll-up progress. Ref: S4.2",
    priority: "P2",
    status: "Todo",
    assigneeUserId: "user-4",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "TSK-305",
    title: "Dependencies + lightweight Gantt (S4.1)",
    description: "Summary: Visualize dependencies and simple schedule shifts. Ref: S4.1",
    priority: "P2",
    status: "Todo",
    assigneeUserId: "user-4",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "TSK-306",
    title: "Iteration planning with capacity (S4.4)",
    description: "Summary: Add capacity hints and overload warnings in planning. Ref: S4.4",
    priority: "P3",
    status: "Todo",
    assigneeUserId: "user-2",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "TSK-307",
    title: "Exportable status reports (UI export) (S2.3)",
    description: "Summary: Generate shareable PDF/CSV status reports from views. Ref: S2.3",
    priority: "P3",
    status: "Todo",
    assigneeUserId: "user-3",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "TSK-308",
    title: "Flow metrics: basic cycle time/throughput (S2.2)",
    description: "Summary: Approximate cycle time based on status change history. Ref: S2.2",
    priority: "P3",
    status: "Todo",
    assigneeUserId: "user-4",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "TSK-309",
    title: "Onboarding guides and templates (S1.3)",
    description: "Summary: Role-based playbooks and checklists for V0. Ref: S1.3",
    priority: "P3",
    status: "Todo",
    assigneeUserId: "user-1",
    projectId: "proj-1",
    teamId: "team-prod",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "TSK-310",
    title: "Transparent pricing/licensing policy (S1.4)",
    description: "Summary: Define plans, limits, and in-app communication. Ref: S1.4",
    priority: "P3",
    status: "Todo",
    assigneeUserId: "user-1",
    projectId: "proj-1",
    teamId: "team-prod",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "TSK-311",
    title: "One‑click data import (prototype) (S1.1)",
    description: "Summary: Prototype mapping/import for simple CSV; sandbox only. Ref: S1.1",
    priority: "P4",
    status: "Todo",
    assigneeUserId: "user-4",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "TSK-312",
    title: "Workflow customization: custom fields/statuses (S4.5)",
    description: "Summary: Minimal custom fields and status presets. Ref: S4.5",
    priority: "P4",
    status: "Todo",
    assigneeUserId: "user-2",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "TSK-313",
    title: "Terminology mapping helpers (S1.5)",
    description: "Summary: Provide glossary and mapping hints (Asana/Jira → FlowCraft). Ref: S1.5",
    priority: "P4",
    status: "Todo",
    assigneeUserId: "user-5",
    projectId: "proj-1",
    teamId: "team-prod",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "TSK-314",
    title: "Lightweight automation rules (S3.3)",
    description: "Summary: Rule builder UI for auto-assign/status changes. Ref: S3.3",
    priority: "P4",
    status: "Todo",
    assigneeUserId: "user-2",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "TSK-315",
    title: "Deep integrations (GitHub/Slack) (S3.1)",
    description: "Summary: Plan bidirectional sync; start with mock webhooks. Ref: S3.1",
    priority: "P5",
    status: "Todo",
    assigneeUserId: "user-4",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "TSK-316",
    title: "Global undo/history (S5.2)",
    description: "Summary: Track state changes for undo across key flows. Ref: S5.2",
    priority: "P5",
    status: "Todo",
    assigneeUserId: "user-3",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "TSK-317",
    title: "Mobile parity (PWA baseline) (S5.4)",
    description: "Summary: Improve responsive layout and offline hints. Ref: S5.4",
    priority: "P5",
    status: "Todo",
    assigneeUserId: "user-2",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "TSK-318",
    title: "Resource allocation views (S2.4)",
    description: "Summary: Workload/Capacity view by user and team. Ref: S2.4",
    priority: "P5",
    status: "Todo",
    assigneeUserId: "user-3",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "TSK-319",
    title: "Goals/OKRs — link to work (S2.5)",
    description: "Summary: Simple goal objects and progress roll-up. Ref: S2.5",
    priority: "P5",
    status: "Todo",
    assigneeUserId: "user-1",
    projectId: "proj-1",
    teamId: "team-prod",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "TSK-320",
    title: "AI assistance: AC drafting/duplicates (S3.5)",
    description: "Summary: Draft AC and detect duplicate issues using LLM API. Ref: S3.5",
    priority: "P5",
    status: "Todo",
    assigneeUserId: "user-2",
    projectId: "proj-1",
    teamId: "team-dev",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
]


export const demoIssueTemplates: IssueTemplate[] = [
  {
    id: "bug",
    name: "Bug",
    prefix: "[Bug] ",
    isDefault: false,
    defaults: {
      priority: "P1",
      status: "Todo",
      defaultAssigneeUserId: "user-1", // Alice Johnson
    },
    acceptanceCriteria: [
      "Steps to reproduce defined",
      "Expected vs actual behavior described",
      "Reproduction confirmed",
    ],
  },
  {
    id: "feature",
    name: "Feature",
    prefix: "[Feature] ",
    isDefault: true,
    defaults: {
      priority: "P3",
      status: "Todo",
      defaultAssigneeUserId: "user-2", // Bob Smith
    },
    acceptanceCriteria: [
      "Acceptance scenarios listed",
      "Non-functional constraints noted",
      "UX mock agreed",
    ],
  },
  {
    id: "request",
    name: "Request",
    prefix: "[Request] ",
    isDefault: false,
    defaults: {
      priority: "P2",
      status: "Todo",
      defaultAssigneeUserId: "user-4", // Charlie Brown
    },
    acceptanceCriteria: [
      "User impact clarified",
      "Success criteria measurable",
      "Approver identified",
    ],
  },
]
